### ISSUE TITLE
This Isnt in your video tutorial but im sure you'll know why it keeps erroring

### ISSUE THREAD

**Issue by KatoOhashi** [Nelderson/MV_Online#108]
error is as stated below 
14:54:33.92 <INFO> Master Server started on port: 8000
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)
Emitted 'error' event at:
    at RedisClient.onError (G:\RPGMaker MV Projects\MV_Online-master\node_modules\socket.io-redis\index.js:118:12)
    at RedisClient.emit (events.js:196:13)
    at RedisClient.on_error (G:\RPGMaker MV Projects\MV_Online-master\node_modules\redis\index.js:406:14)
    at Socket.<anonymous> (G:\RPGMaker MV Projects\MV_Online-master\node_modules\redis\index.js:279:14)
    at Socket.emit (events.js:196:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mvonline@0.2.2 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mvonline@0.2.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by KatoOhashi** [comment]
im actually Seeing where it keeps erroring in the REDISCLIENT but i dont want to touch that code cuase it wasnt in the video tutorial

**Comment by squareware** [comment]
It seems like your redis server is not installed / running?

**Comment by KatoOhashi** [comment]
oof how to install e.e it wasnt included in the video tutorial in the server part ??? oof ???

**Comment by KatoOhashi** [comment]
Bumporino 
ahem 
 how to install??? it wasnt included in the video tutorial in the server part

**Comment by KatoOhashi** [comment]
ok well apparently i fixed my issue solo on this one but more issues ahead apprently too theres alot of deprications in your work and server crashes when a player logs in
i will write more on that in a different ticket To see if it helps fix those for you 
but im gonna take a nights rest first @~@

**Comment by squareware** [comment]
Relax a bit dude,

First its not mine work, its a work in progress by Nelderson. 

The new setup files comes with some flaws, bugs and a documentation that’s not yet up to date.

 

Making use of the old files / setup could help you going following the youtube vids from a year or so ago.. 
Also feel free to join the discord to help you solve your problems faster and help others with their problems.

 

Discord:
Discord.ggKZqBqK

**Comment by Soubi92** [comment]
@squareware Where can I find the old data files?

**Comment by squareware** [comment]
Click a file on the github and click history.

**Comment by rafaelrodrigosilveira** [comment]
I fix this in the config.js, in the line 23:
redisConnection: process.env.MV_REDIS_HOST_URL || 'redis://localhost',

change this for:
redisConnection: process.env.MV_REDIS_HOST_URL || 'redis://url_mongo:port',
