### ISSUE TITLE
Error Redis: failed to connect in mongoDB

### ISSUE THREAD

**Issue by rafaelrodrigosilveira** [Nelderson/MV_Online#111]
Hello friend.

I have to installed node.js and npm install -d and npm start. But this error appear:

Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
Emitted 'error' event at:
    at RedisClient.onError (C:\MV_Online\node_modules\socket.io-redis\index.js:118:12)
    at RedisClient.emit (events.js:198:13)
    at RedisClient.on_error (C:\MV_Online\node_modules\redis\index.js:406:14)
    at Socket.<anonymous> (C:\MV_Online\node_modules\redis\index.js:279:14)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mvonline@0.2.2 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mvonline@0.2.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Maybe error in REDIS module?

**Comment by CaoQuocTuan** [comment]
you need install redis and run it before start server.
https://github.com/dmajkic/redis/downloads

**Comment by rafaelrodrigosilveira** [comment]
I fix this in the config.js, in the line 23:
redisConnection: process.env.MV_REDIS_HOST_URL || 'redis://localhost',

change this for:
redisConnection: process.env.MV_REDIS_HOST_URL || 'redis://url_mongo:port',

**Comment by rafaelrodrigosilveira** [comment]
I fix this in the config.js, in the line 23:
redisConnection: process.env.MV_REDIS_HOST_URL || 'redis://localhost',

change this for:
redisConnection: process.env.MV_REDIS_HOST_URL || 'redis://url_mongo:port',
