### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by AveAcVale** [Nelderson/MV_Online#113]
events.js:167
      throw er; // Unhandled 'error' event
      ^
AbortError: Ready check failed: Redis connection lost and command aborted. It might have been processed.
    at RedisClient.flush_and_error (A:\Downloads\MV_Online-master\node_modules\redis\index.js:362:23)
    at RedisClient.connection_gone (A:\Downloads\MV_Online-master\node_modules\redis\index.js:664:14)
    at Socket.<anonymous> (A:\Downloads\MV_Online-master\node_modules\redis\index.js:293:14)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at RedisClient.onError (A:\Downloads\MV_Online-master\node_modules\socket.io-redis\index.js:118:12)
    at RedisClient.emit (events.js:182:13)
    at RedisClient.on_info_cmd (A:\Downloads\MV_Online-master\node_modules\redis\index.js:496:14)
    at A:\Downloads\MV_Online-master\node_modules\redis\index.js:535:14
    at Object.callbackOrEmit [as callback_or_emit] (A:\Downloads\MV_Online-master\node_modules\redis\lib\utils.js:89:9)
    at Command.callback (A:\Downloads\MV_Online-master\node_modules\redis\lib\individualCommands.js:157:15)
    at RedisClient.flush_and_error (A:\Downloads\MV_Online-master\node_modules\redis\index.js:374:29)
    at RedisClient.connection_gone (A:\Downloads\MV_Online-master\node_modules\redis\index.js:664:14)
    [... lines matching original stack trace ...]
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mvonline@0.2.2 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mvonline@0.2.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Cookie Twister\AppData\Roaming\npm-cache\_logs\2019-07-29T20_37_51_717Z-debug.log
![2019-07-30_06-40-13](https://user-images.githubusercontent.com/7797347/62080835-bc907b00-b294-11e9-8b5b-a396950fb9b8.png)

**Comment by squareware** [comment]
Hi Mamoru,

 

I have the same issue doing the reddis with a windows rig.
For the time being, you could use the old files without the redis, which works great on windows.

I’m sure Nelderson will come up with a fix for it.



 

Van: Mamoru Trouble [mailto:notifications@github.com] 
Verzonden: maandag 29 juli 2019 22:39
Aan: Nelderson/MV_Online
CC: Subscribed
Onderwerp: [Nelderson/MV_Online] Server crash (#113)

 

events.js:167
throw er; // Unhandled 'error' event
^
AbortError: Ready check failed: Redis connection lost and command aborted. It might have been processed.
at RedisClient.flush_and_error (A:\Downloads\MV_Online-master\node_modules\redis\index.js:362:23)
at RedisClient.connection_gone (A:\Downloads\MV_Online-master\node_modules\redis\index.js:664:14)
at Socket. (A:\Downloads\MV_Online-master\node_modules\redis\index.js:293:14)
at Object.onceWrapper (events.js:273:13)
at Socket.emit (events.js:187:15)
at endReadableNT (_stream_readable.js:1094:12)
at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
at RedisClient.onError (A:\Downloads\MV_Online-master\node_modules\socket.io-redis\index.js:118:12)
at RedisClient.emit (events.js:182:13)
at RedisClient.on_info_cmd (A:\Downloads\MV_Online-master\node_modules\redis\index.js:496:14)
at A:\Downloads\MV_Online-master\node_modules\redis\index.js:535:14
at Object.callbackOrEmit [as callback_or_emit] (A:\Downloads\MV_Online-master\node_modules\redis\lib\utils.js:89:9)
at Command.callback (A:\Downloads\MV_Online-master\node_modules\redis\lib\individualCommands.js:157:15)
at RedisClient.flush_and_error (A:\Downloads\MV_Online-master\node_modules\redis\index.js:374:29)
at RedisClient.connection_gone (A:\Downloads\MV_Online-master\node_modules\redis\index.js:664:14)
[... lines matching original stack trace ...]
at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mvonline@0.2.2 start: node server.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mvonline@0.2.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\Cookie Twister\AppData\Roaming\npm-cache_logs\2019-07-29T20_37_51_717Z-debug.log
 <https://user-images.githubusercontent.com/7797347/62080835-bc907b00-b294-11e9-8b5b-a396950fb9b8.png> 2019-07-30_06-40-13
