### ISSUE TITLE
Error NPM START

### ISSUE THREAD

**Issue by rafaelrodrigosilveira** [Nelderson/MV_Online#40]
Helo Nelderson. Conglatullation from this project.

I have been trying to start server, but this is not work. Appear this message above:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle mvonline@0.2.2~prestart: mvonline@0.2.2
6 silly lifecycle mvonline@0.2.2~prestart: no script for prestart, continuing
7 info lifecycle mvonline@0.2.2~start: mvonline@0.2.2
8 verbose lifecycle mvonline@0.2.2~start: unsafe-perm in lifecycle true
9 verbose lifecycle mvonline@0.2.2~start: PATH: /usr/share/npm/bin/node-gyp-bin:/home/ubuntu/mv_server/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle mvonline@0.2.2~start: CWD: /home/ubuntu/mv_server
11 silly lifecycle mvonline@0.2.2~start: Args: [ '-c', 'node server.js' ]
12 silly lifecycle mvonline@0.2.2~start: Returned: code: 1  signal: null
13 info lifecycle mvonline@0.2.2~start: Failed to exec start script
14 verbose stack Error: mvonline@0.2.2 start: `node server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid mvonline@0.2.2
16 verbose cwd /home/ubuntu/mv_server
17 error Linux 4.4.0-98-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v4.2.6
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error mvonline@0.2.2 start: `node server.js`
22 error Exit status 1
23 error Failed at the mvonline@0.2.2 start script 'node server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the mvonline package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs mvonline
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls mvonline
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

Please, help me friend.

**Comment by rafaelrodrigosilveira** [comment]
I solved this. Thanks.
