### ISSUE TITLE
Don't send email link to activate

### ISSUE THREAD

**Issue by rafaelrodrigosilveira** [Nelderson/MV_Online#42]
Hi, conglatulations by server.

I've been take this error when the users make a user. When the server send email to activate, appear this message e don't send email. Somebody to help me?

**ERROR DISPLAYED:**

(node:3252) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 1): Error: self signed certificate in certificate chain
(node:3252) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

**Comment by rafaelrodrigosilveira** [comment]
Hi, thanks for answer. The log paper this:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle mvonline@0.2.2~prestart: mvonline@0.2.2
6 info lifecycle mvonline@0.2.2~start: mvonline@0.2.2
7 verbose lifecycle mvonline@0.2.2~start: unsafe-perm in lifecycle true
8 verbose lifecycle mvonline@0.2.2~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Rafael\Documents\GitHub\MV_Online\server\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Git\cmd;C:\Program Files\nodejs\;C:\Users\Rafael\AppData\Roaming\npm
9 verbose lifecycle mvonline@0.2.2~start: CWD: C:\Users\Rafael\Documents\GitHub\MV_Online\server
10 silly lifecycle mvonline@0.2.2~start: Args: [ '/d /s /c', 'node server.js' ]
11 silly lifecycle mvonline@0.2.2~start: Returned: code: 1  signal: null
12 info lifecycle mvonline@0.2.2~start: Failed to exec start script
13 verbose stack Error: mvonline@0.2.2 start: `node server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid mvonline@0.2.2
15 verbose cwd C:\Users\Rafael\Documents\GitHub\MV_Online\server
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.9.1
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error mvonline@0.2.2 start: `node server.js`
22 error Exit status 1
23 error Failed at the mvonline@0.2.2 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
