### ISSUE TITLE
<ERROR> Self signed certificate in certificate chain

### ISSUE THREAD

**Issue by Akimixu** [Nelderson/MV_Online#77]
Hey,

After successfully connecting to MongoDB, I tried to registrate a new "test" account, and it appears on MongoDB:

 >{
    "_id": {
        "$oid": "5ae8a1304957d7239caf912a"
    },
    "salt": "3941bcaa418250550afc9d2b9ec46901c0b8a036f3dd8086118d9b9b5161b785",
    "hash": "8765e04e42defc7316cb9f5ddbf71c83ab5b62c52d4f935ba6ba5bda335598a0b40017f7fab9e22c4dff84973fc38359eef59beb82b91f3beda97c025a5af05bcd46505f36af8a8f9bd02e48521f77d47ebc8aa4ab2faf5602df9a0a013c34c559f47e773085ecd040b10a278f0ef4eab31ae318a9c5062f06d512379b2460dbf638ad54f8255eaa49ebb53a3f7f98fe07b1fa5ab90b90cca4ff6748cb4d1673cd8cbd61127ae8f73646fcf27d90e8b3ea892676ea6149014c4488670dde16150e157fb934e9479dc4e6cf70b535adbe9d81e9c7dad3a726f6697152be8a1cf647f3344f048228d248360c4b4b400cc5a41ca2fbd2d6880b3cee4e13887ec926d0b10ecde1b7a9b858d1820aebd869bfeaded738c9cb9f0b9a41c540f61afa0120e5878a92966ebf8248ee872d5d6c0c96477635072c370da489f61afdd9262c300944c4c675cc7003fb4675989e33d19ca3c071efb50650b234ca9919082188f8ca4cc727d533694af3c501fa404ac40f185a8bd0c04b9d31a18b762d0a3caeef16c4a7b916ef7692936c87bd9bfccfa747239a708ae1b5cf733cd1d6bfd1aad9cfa44243114daa717cb5453f28b594bbcd76efde44594dc336590fe420a142be4a90e9ad64629d8b4c9a0e23b08b78c499e292785da509af96c512721c284752075c489ffecef990d596bb5e584a72df005c4fd5b7b05d9421182bad19f034",
    "username": "pba2",
    "email": "gti93705@ckoie.com",
    "activated": false,
    "actCode": "3a8abddef44e0a9b65f72edaa1002c96557d6cd4",
    "socketId": null,
    "rank": 0,
    "__v": 0
}

Apparently, the account isn't activated yet, but I never got any activation mail (BTW, I already tried registrating a Gmail account). I use GMail as mailFrom, and already allowed unsafe apps and Unlockcaptcha.

This is what the console shows me after trying to register:

> POST /register 200 2636.495 ms - 78
12:38:41.19 <ERROR> { Error: self signed certificate in certificate chain
    at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38) code: 'ECONNECTION', command: 'CONN' } (in login_routes.js:71)
Call Stack:
    at C:\Users\Usuario\Desktop\MV_Online-master\server\api_routes\login_routes.js:71:21
    at transporter.send.args (C:\Users\Usuario\Desktop\MV_Online-master\server\node_modules\nodemailer\lib\mailer\index.js:224:21)
    at SMTPConnection.connection.once.err (C:\Users\Usuario\Desktop\MV_Online-master\server\node_modules\nodemailer\lib\smtp-transport\index.js:174:24)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at SMTPConnection.emit (events.js:211:7)
    at SMTPConnection._onError (C:\Users\Usuario\Desktop\MV_Online-master\server\node_modules\nodemailer\lib\smtp-connection\index.js:596:14)
    at TLSSocket._socket.on.err (C:\Users\Usuario\Desktop\MV_Online-master\server\node_modules\nodemailer\lib\smtp-connection\index.js:265:18)
    at emitOne (events.js:116:13)

What am I doing wrong? Do you need anything else?

**Comment by Nelderson** [comment]
I know for a fact gmail does work, but google constantly changes the workaround for this.  Google would be much accurate with the how-tos.
